position_colors = {
    'Goalie': 'white',
    'Center/R.Wing': 'pink',
    'Left Wing': 'blue',
    'Forward': 'yellow',
    'Right Wing': 'red',
    'Defence': 'cyan',
    'Center': 'magenta',
    'Right Defence': 'orange',
    'Center/L.Wing': 'grey',
    'Wing': 'green',
    'Left Defence': 'lime',
    'D': 'cyan',
    'F': 'yellow',
    'G': 'white',
    'C': 'magenta',
    'R': 'red',
    'L': 'blue',
}